/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Brian
 */
public class manageTransactionForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(manageTransactionForm.class.getName());

    private int loggedInUserId;
    private String userRole;

    /**
     * Creates new form manageTransactionForm
     */
    public manageTransactionForm(int userId, String role) {
        initComponents();
        this.loggedInUserId = userId;
        this.userRole = role;
        loadData();
    }

    private void loadData() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblTransaction.getModel();
        model.setRowCount(0);

        dao.TransactionDAO transactionDAO = new dao.TransactionDAO();
        java.util.List<model.TransactionModel> list = transactionDAO.getAllTransactions();

        for (model.TransactionModel trans : list) {
            model.addRow(new Object[]{
                trans.getTransactionId(),
                trans.getMemberId(),
                trans.getBookId(),
                trans.getProcessedBy(),
                trans.getBorrowDate(),
                trans.getReturnDate(),
                trans.getStatus()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBookId = new javax.swing.JTextField();
        txtMemberId = new javax.swing.JTextField();
        btnBorrow = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTransaction = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtBookId.setText("jTextField1");

        txtMemberId.setText("jTextField1");

        btnBorrow.setText("Borrow");
        btnBorrow.addActionListener(this::btnBorrowActionPerformed);

        btnReturn.setText("Return It");
        btnReturn.addActionListener(this::btnReturnActionPerformed);

        btnBack.setText("jButton1");
        btnBack.addActionListener(this::btnBackActionPerformed);

        tblTransaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblTransaction);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBookId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBorrow)
                            .addComponent(btnReturn))))
                .addContainerGap(283, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        int baris = tblTransaction.getSelectedRow();
        if (baris == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih dulu data transaksi di tabel yang mau dikembalikan!");
            return;
        }

        int transactionId = Integer.parseInt(tblTransaction.getValueAt(baris, 0).toString());
        String status = tblTransaction.getValueAt(baris, 6).toString();

        if (status.equals("returned")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Buku ini sudah dikembalikan sebelumnya.");
            return;
        }

        java.sql.Date returnDate = new java.sql.Date(System.currentTimeMillis());
        dao.TransactionDAO transactionDAO = new dao.TransactionDAO();

        if (transactionDAO.returnBook(transactionId, returnDate)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Buku berhasil dikembalikan!");
            loadData();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memproses pengembalian.");
        }
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (userRole.equals("admin")) {
            view.AdminDashboard adminDash = new view.AdminDashboard(loggedInUserId);
            adminDash.setVisible(true);
        } else if (userRole.equals("staff")) {
            view.StaffDashboard staffDash = new view.StaffDashboard(loggedInUserId);
            staffDash.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrowActionPerformed
        int memberId = Integer.parseInt(txtMemberId.getText());
        int bookId = Integer.parseInt(txtBookId.getText());
        java.sql.Date borrowDate = new java.sql.Date(System.currentTimeMillis());

        model.TransactionModel trans = new model.TransactionModel(memberId, bookId, loggedInUserId, borrowDate, "borrowed");
        dao.TransactionDAO transactionDAO = new dao.TransactionDAO();

        if (transactionDAO.borrowBook(trans)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Buku berhasil dipinjam!");
            loadData();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal memproses peminjaman.");
        }
    }//GEN-LAST:event_btnBorrowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new manageTransactionForm(2, "admin").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBorrow;
    private javax.swing.JButton btnReturn;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTransaction;
    private javax.swing.JTextField txtBookId;
    private javax.swing.JTextField txtMemberId;
    // End of variables declaration//GEN-END:variables
}
